<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php

$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$deviceBlock = $block->getLayout()->createBlock('Orange\Intermediate\Block\Item');
$deviceViewBlock = $block->getLayout()->createBlock('Orange\Catalog\Block\Product\CustomView');
$brands = $deviceBlock->getBrands();
$sortVal = $this->getRequest()->getParam('sort');
$sortdirVal = $this->getRequest()->getParam('dir');
$brandVal = $this->getRequest()->getParam('brand');
$searchVal = $this->getRequest()->getParam('search');
$currentStoreId = $block->getCurrentStoreId();
$_catalogHelper = $this->helper('Orange\Catalog\Helper\CatalogUrl');
$priceLabel = $block->getPriceLabel();

$finalCollectionBrandids = $block->getcurproductcollection();

// Check Tealium Module output status //
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$scopeConfig = $objectManager->create('Magento\Framework\App\Config\ScopeConfigInterface');
$tealiumStatus = $scopeConfig->getValue('tags/general/enabled', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
if($tealiumStatus){
	$udoBlock = $block->getLayout()->createBlock('Tealium\Tags\Block\DefaultUdo');
	$utagProductData = array();
	$udodata = $udoBlock->getUTagData();
}
?>
<?php echo $block->getToolbarHtml() ?>
<?php echo $block->getAdditionalHtml() ?>
<span id="productlist-count" style="display:none"><?php echo $block->GetListingCount(); ?></span><!-- Required to get pagination correctly while grouping-->
<?php if (!$_productCollection->count()): ?>
	<div style="background-color:#fdf0d5;"><div class="container">
    <div class="message info empty" style="margin: 0px 0px 0px -10px;"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
	</div></div>
	<section>
		<div class="region region-content">
			<section id="block-system-main" class="block block-system clearfix">
			<?php $currentpage = $this->getRequest()->getParam('p'); ?>
			 <?php if (!$currentpage): ?>
				<article class="node node-landing-page style-layer-style--blue clearfix">
					<div class="landing-page-top-wrapper wrapper-with-image margin-xs-b-n">
						<div class="container landing-page-top">
							<div class="field field-name-field-display-title field-type-text field-label-hidden" style="margin-top:20px;">
								<div class="field-items">
									<div class="field-item even">
										<h1>
											<?php if ($currentCategory = $block->getCurrentCategory()): ?>
												<?php echo $currentCategory->getName(); ?>
											<?php endif; ?>
										</h1>
									</div>
								</div>
							</div>
							<div class="row margin-xs-v-m smartphone-hero product-item">
								<?php
								$bannerItems = $block->getBannerSmartphoneDevices();
								$i=1;
								foreach($bannerItems as $bannerItem):
								$familyType = 'smartphone';
								$stockProduct = $block->getHighStockProduct($bannerItem->getHandsetFamily(),$familyType);
								if(!$stockProduct->getId())
								{
									$stockProduct = $bannerItem;
								}
								$colorName  = $_catalogHelper->getColorOption($stockProduct);
								$productTitle = str_replace($colorName,"",$stockProduct->getName());
								$alt_tag = __('Orange Belgique').' - '.$productTitle.' - '.$colorName;
								?>
								<div class="col-xs-12 col-sm-6">
									<div class="media phone-item no-border margin-xs-t-n">
										<div class="media-left pull-left">
											<div class="margin-xs-v-s">
												<?php
												$imageUrl = $this->helper('Magento\Catalog\Helper\Image')
													->init($stockProduct, 'intermediate_page_image_medium')
													->setImageFile($stockProduct->getFile())
													->getUrl();
													?>
												<img src="<?php echo $imageUrl; ?>" alt = "<?php echo trim($alt_tag); ?>">
											</div>
										</div>
										<div class="media-body">
											<?php $handsetName = $stockProduct->getHandsetFamily();?>
											<?php if (str_word_count($handsetName)>1):?>
												<?php $arr = explode(' ',trim($handsetName));?>
												<h3 class="js-matchBoxHeight margin-xs-t-s blue-bar-heading">
												<?php echo nl2br($arr[0]."\n".substr(strstr($handsetName," "), 1));?>
												</h3>
											<?php else:?>
												<h3 class="js-matchBoxHeight margin-xs-t-s blue-bar-heading"><?php /* @escapeNotVerified */ echo __($stockProduct->getHandsetFamily()); ?></h3>
											<?php endif?>
											<?php
											//$family = $deviceBlock->getDeviceFamilyText($bannerItem); //Device family
											$familyId = $bannerItem->getHandsetFamily();
											$availableColors = $deviceBlock->getAvailableColors($familyId);
											if($this->getCustomerTypeName()=='SOHO'):
												$subscriptionPrice = $bannerItem->getMinSohoSubsidyPrice();
											else:
												$subscriptionPrice = $bannerItem->getMinSubsidyPrice();
											endif;
											?>
											<?php if(count($availableColors) > 1): ?>
												<p><?php  echo __('Disponible en %1 couleurs', count($availableColors)) ?></p>
											<?php ?>
											<?php endif; ?>

											<?php if($stockProduct->getObsoleteDevice() == 1): ?>
												<p class="red"><?php /* @escapeNotVerified */ echo __('Epuisé') ?></p>
											<?php else: ?>
												<?php if($stockProduct->isAvailable()):?>
													<p class="white"><?php /* @escapeNotVerified */ echo __('En stock') ?></p>
												<?php else: ?>
													<p class="white"><?php /* @escapeNotVerified */ echo __('Indisponible') ?></p>
												<?php endif; ?>
											<?php endif; ?>
											<?php $tierPrice = $stockProduct->getPriceInfo()->getPrice('final_price')->getAmount()->getValue(); ?>
											<?php
											    $currentBannerProduct = $block->getSubscription($bannerItem->getId());
                                                $linkedHeroTariff = '';
                                                if($this->getCustomerTypeName()=='SOHO'):
												     $linkedHeroTariff = $currentBannerProduct->getResource()->getAttribute('linked_hero_tariff_soho')->getFrontend()->getValue($currentBannerProduct);
                                                else:
													$linkedHeroTariff = $currentBannerProduct->getResource()->getAttribute('linked_hero_tariff_b2c')->getFrontend()->getValue($currentBannerProduct);
                                                endif;
												$bannerVirtualProduct = $block->getBannerUpSellProduct($currentBannerProduct,$linkedHeroTariff);
											?>
                                                                                        <!-- hiding price for obsoletedevice -->
                                                                                        <?php if($stockProduct->getObsoleteDevice() != 1): ?>
                                                                                            <?php if($bannerVirtualProduct): $priceClass = 'lob old-price'; else: $priceClass ='lob new-price white'; endif; ?>
                                                                                            <?php if(!$bannerVirtualProduct):?>
                                                                                            <?php echo $block->getOrangePricingHtml($tierPrice,true,true,false,$priceClass); ?>
                                                                                            <?php else: ?>
                                                                                            <?php echo $block->getOrangePricingHtml($tierPrice,true,true,false,$priceClass); ?>
                                                                                            <?php endif; ?>
                                                                                            <?php
                                                                                                    if($bannerVirtualProduct):
                                                                                                            $subscription = $block->getSubscription($bannerItem->getSubscriptionId());
                                                                                                    ?>
                                                                                                    <?php echo $block->getOrangePricingHtml($bannerVirtualProduct['price'],true,true,false,'lob new-price white'); ?>
                                                                                                    <p class=""><?php echo __('avec ').$bannerVirtualProduct ['name']; ?> </p>
                                                                                            <?php endif;?>
                                                                                        <?php endif; ?>
                                                                                        <!-- end -->
											<?php $formattedUrl = $_catalogHelper->getFormattedUrl($stockProduct->getProductUrl()); ?>
											<div class="clearfix"></div>
										</div>
									</div>
									<div class="<?php if($this->getCustomerTypeName()=='SOHO'):?>blue-bar-bttn-soho<?php else:?>blue-bar-bttn<?php endif; ?>">
										<a class="btn btn-default margin-xs-b-l <?php if($currentStoreId == 2): ?>caddy-cta-fr<?php else:?>caddy-cta<?php endif;?>" href="<?php echo $formattedUrl; ?>"><?php /* @escapeNotVerified */ echo __("Plus d'infos") ?></a>
									</div>
								</div>
								<?php $i++; ?>
								<?php endforeach;
								?>
							</div>
						</div>
					</div>
				</article>
				<?php endif; ?>
			<article class="node node-layer-columns layer-style--gray clearfix">
				<?php $selected = "background-color: #ffffff;color:black"; ?>
					<div class="container">
						<div class="row">
							<div class="col-sm-12 col-md-2 padding-xs-b-s padding-sm-b-s padding-md-b-n">
								<span class="font-24"><?php echo __('Rechercher') ?></span>
							</div>
							<div class="col-sm-12 col-md-4 padding-xs-b-s padding-sm-b-s padding-md-b-n">
								<input class="form-control search-device" autocomplete="off" value="<?php echo $searchVal ?>" type="text" name="USER" id="sso-email" placeholder="<?php echo __('Par mots-clés') ?>">
							</div>
							<div class="col-sm-12 col-md-3 padding-xs-b-s padding-sm-b-s padding-md-b-n">
								<div class="">
									 <select class="dropdown-menu-1" name="brandfilter" id="brandfilter" >
										<option value=""><?php echo __('Toutes les marques') ?></option>
										<?php foreach($brands as $brand): ?>
										<?php if($brand->getValue()!='' && in_array($brand->getValue(), $finalCollectionBrandids)): ?>
										<option  value="<?php echo $brand->getValue(); ?>" <?php if($brandVal == $brand->getValue()):?> selected <?php endif; ?>><?php echo $brand->getLabel(); ?></option>
                                       	<?php endif; ?>
										<?php endforeach; ?>
                                        </select>
								</div>
							</div>
							<div class="col-sm-12 col-md-3 padding-xs-b-s padding-sm-b-s padding-md-b-n">
								<div class="">
									<select class="dropdown-menu-1" name="sortby" id="sortby">
										<option value="" ><?php echo __('Par prix') ?></option>
										<option  value="sort=price&dir=asc" <?php if($sortVal == 'price' && $sortdirVal == 'asc'):?> selected<?php endif; ?>  ><?php echo __('Croissant Prix Standalone') ?></option>
                                        <option  value="sort=subscription&dir=desc" <?php if($sortVal == 'subscription' && $sortdirVal == 'desc'):?> selected<?php endif; ?> ><?php echo __('Croissant Prix de subvention') ?></option>
                                        <option  value="sort=price&dir=desc" <?php if($sortVal == 'price' && $sortdirVal == 'desc'):?> selected<?php endif; ?> ><?php echo __('Prix decroissant Standalone') ?></option>
                                        <option  value="sort=subscription&dir=asc" <?php if($sortVal == 'subscription' && $sortdirVal == 'asc'):?> selected<?php endif; ?> ><?php echo __('Prix decroissant de subvention') ?></option>
                                    </select>
								</div>
							</div>
						</div>
					</div>
				</article>
			</section>
			</div>
			</section>
	<?php else: ?>
	<section>
		<div class="region region-content">
			<section id="block-system-main" class="block block-system clearfix">
			<?php $currentpage = $this->getRequest()->getParam('p'); ?>
			 <?php if (!$currentpage): ?>
				<article class="node node-landing-page style-layer-style--blue clearfix">

					<div class="landing-page-top-wrapper wrapper-with-image margin-xs-b-n">
						<div class="container landing-page-top">
							<div class="field field-name-field-display-title field-type-text field-label-hidden" style="margin-top:20px;">
								<div class="field-items">
									<div class="field-item even">
										<h1>
											<?php if ($currentCategory = $block->getCurrentCategory()): ?>
												<?php echo $currentCategory->getName(); ?>
											<?php endif; ?>
										</h1>
									</div>
								</div>
							</div>
							<div class="row margin-xs-v-m smartphone-hero product-item">
								<?php
								$bannerItems = $block->getBannerSmartphoneDevices();
								$i=1;
								$bannerOffset = 0;
								foreach($bannerItems as $bannerItem):
								$familyType = 'smartphone';
								$stockProduct = $block->getHighStockProduct($bannerItem->getHandsetFamily(),$familyType);
								if(!$stockProduct->getId())
								{
									$stockProduct = $bannerItem;
								}
								/** Tealium Tag Data of hero product *********/
								if($tealiumStatus){
									$udodata['product_category'][] 	= strtolower($udoBlock->getAttributesValue($stockProduct,'tealium_product_category'));
									$udodata['product_type'][] 		= strtolower($udoBlock->getAttributesValue($stockProduct,'tealium_product_type'));
									$udodata['product_brand'][] 	= strtolower($udoBlock->getAttributesValue($stockProduct,'brand'));
									$udodata['product_sku'][] 		= $stockProduct->getSku();
									$udodata['product_name'][] 		= strtolower($stockProduct->getTealiumPageName());
									$udodata['product_unit_price'][]= str_replace(",","",number_format($stockProduct->getPrice('final_price'),2));
								}
								$colorName  = $_catalogHelper->getColorOption($stockProduct);
								$productTitle = str_replace($colorName,"",$stockProduct->getName());
								$alt_tag = __('Orange Belgique').' - '.$productTitle.' - '.$colorName;
                                $bannerOffset++;
								?>
								<div class="col-xs-12 col-sm-5 <?php if ($bannerOffset % 2 == 0):?> col-sm-offset-2<?php endif;?>">
									<div class="media phone-item no-border margin-xs-t-n">
										<div class="media-left pull-left">
											<div class="margin-xs-v-s">
												<?php
												$imageUrl = $this->helper('Magento\Catalog\Helper\Image')
													->init($stockProduct, 'intermediate_page_image_medium')
													->setImageFile($stockProduct->getFile())
													->getUrl();
													?>
												<img src="<?php echo $imageUrl; ?>" alt = "<?php echo trim($alt_tag); ?>">
											</div>
										</div>
										<div class="media-body">
											<?php $handsetName = $stockProduct->getHandsetFamily();?>
											<?php if (str_word_count($handsetName)>1):?>
												<?php $arr = explode(' ',trim($handsetName));?>
												<h3 class="js-matchBoxHeight margin-xs-t-s blue-bar-heading">
												<?php echo nl2br($arr[0]."\n".substr(strstr($handsetName," "), 1));?>
												</h3>
											<?php else:?>
												<h3 class="js-matchBoxHeight margin-xs-t-s blue-bar-heading"><?php /* @escapeNotVerified */ echo __($stockProduct->getHandsetFamily()); ?></h3>
											<?php endif?>
											<?php
											//$family = $deviceBlock->getDeviceFamilyText($bannerItem); //Device family
											$familyId = $bannerItem->getHandsetFamily();
											$availableColors = $deviceBlock->getAvailableColors($familyId);
											if($this->getCustomerTypeName()=='SOHO'):
												$subscriptionPrice = $bannerItem->getMinSohoSubsidyPrice();
											else:
												$subscriptionPrice = $bannerItem->getMinSubsidyPrice();
											endif;
											?>
											<?php if(count($availableColors) > 1): ?>
												<p><?php  echo __('Disponible en %1 couleurs', count($availableColors)) ?></p>
											<?php ?>
											<?php endif; ?>
											<?php if($stockProduct->getObsoleteDevice() == 1): ?>
												<p class="red"><?php /* @escapeNotVerified */ echo __('Epuisé') ?></p>
											<?php else: ?>
												<?php if($stockProduct->isAvailable()):?>
													<p class="white"><?php /* @escapeNotVerified */ echo __('En stock') ?></p>
												<?php else: ?>
													<p class="red"><?php /* @escapeNotVerified */ echo __('Indisponible') ?></p>
												<?php endif; ?>
											<?php endif; ?>
											<?php $tierPrice = $stockProduct->getPriceInfo()->getPrice('final_price')->getAmount()->getValue(); ?>
											 <?php
											   $currentBannerProduct = $block->getSubscription($bannerItem->getId());
                                                $linkedHeroTariff = '';
                                                if($this->getCustomerTypeName()=='SOHO'):
												     $linkedHeroTariff = $currentBannerProduct->getResource()->getAttribute('linked_hero_tariff_soho')->getFrontend()->getValue($currentBannerProduct);
                                                else:
													$linkedHeroTariff = $currentBannerProduct->getResource()->getAttribute('linked_hero_tariff_b2c')->getFrontend()->getValue($currentBannerProduct);
                                                endif;
												$bannerVirtualProduct = $block->getBannerUpSellProduct($currentBannerProduct,$linkedHeroTariff);
											?>
                                                                                        <!-- hiding price for obsoletedevice -->
                                                                                        <?php if($stockProduct->getObsoleteDevice() != 1): ?>
                                                                                            <?php if($bannerVirtualProduct): $priceClass = 'lob old-price'; else: $priceClass ='lob new-price white'; endif; ?>
                                                                                            <?php if(!$bannerVirtualProduct):?>
                                                                                            <?php echo $block->getOrangePricingHtml($tierPrice,true,true,false,$priceClass); ?>
                                                                                            <?php else: ?>
                                                                                            <?php echo $block->getOrangePricingHtml($tierPrice,true,true,false,$priceClass); ?>
                                                                                            <?php endif; ?>
                                                                                            <?php
                                                                                                    if($bannerVirtualProduct):
                                                                                                            $subscription = $block->getSubscription($bannerItem->getSubscriptionId());
                                                                                                    ?>
                                                                                                    <?php echo $block->getOrangePricingHtml($bannerVirtualProduct['price'],true,true,false,'lob new-price white'); ?>
                                                                                                    <p class=""><?php echo __('avec ').$bannerVirtualProduct ['name']; ?> </p>
                                                                                            <?php endif;?>
                                                                                        <?php endif;?>
											<?php $formattedUrl = $_catalogHelper->getFormattedUrl($stockProduct->getProductUrl()); ?>
											<div class="clearfix"></div>
										</div>
									</div>
									<div class="<?php if($this->getCustomerTypeName()=='SOHO'):?>blue-bar-bttn-soho<?php else:?>blue-bar-bttn<?php endif; ?>">
										<a class="btn btn-default margin-xs-b-l <?php if($currentStoreId == 2): ?>caddy-cta-fr<?php else:?>caddy-cta<?php endif;?>" href="<?php echo $formattedUrl; ?>"><?php /* @escapeNotVerified */ echo __("Plus d'infos") ?></a>
									</div>
								</div>
								<?php $i++; ?>
								<?php endforeach;
								?>
							</div>
						</div>
					</div>
				</article>
                <?php endif; ?>
				<div data-aw-csblock-block-name="csblock_category_before_tab"></div>
				<article class="node node-layer-columns layer-style--gray clearfix">
				<?php $selected = "background-color: #ffffff;color:black"; ?>
					<div class="container">
						<div class="row">
							<div class="col-sm-12 col-md-2 padding-xs-b-s padding-sm-b-s padding-md-b-n">
								<span class="font-24"><?php echo __('Rechercher') ?></span>
							</div>
							<div class="col-sm-12 col-md-4 padding-xs-b-s padding-sm-b-s padding-md-b-n">
								<input class="form-control search-device" autocomplete="off" value="<?php echo $searchVal ?>" type="text" name="USER" id="sso-email" placeholder="<?php echo __('Par mots-clés') ?>">
							</div>
							<div class="col-sm-12 col-md-3 padding-xs-b-s padding-sm-b-s padding-md-b-n">
								<div class="">
									 <select class="dropdown-menu-1" name="brandfilter" id="brandfilter" >
										<option value=""><?php echo __('Toutes les marques') ?></option>
										<?php foreach($brands as $brand): ?>
										<?php if($brand->getValue()!='' && in_array($brand->getValue(), $finalCollectionBrandids)): ?>
										<option  value="<?php echo $brand->getValue(); ?>" <?php if($brandVal == $brand->getValue()):?> selected <?php endif; ?>><?php echo $brand->getLabel(); ?></option>
                                       	<?php endif; ?>
										<?php endforeach; ?>
                                        </select>
								</div>
							</div>
							<div class="col-sm-12 col-md-3 padding-xs-b-s padding-sm-b-s padding-md-b-n">
								<div class="">
									   <select class="dropdown-menu-1" name="sortby" id="sortby">
										<option value="" ><?php echo __('Par prix') ?></option>
										<option  value="sort=price&dir=asc" <?php if($sortVal == 'price' && $sortdirVal == 'asc'):?> selected<?php endif; ?>  ><?php echo __('Oplopend zonder abonnement') ?></option>
                                        <option  value="sort=subscription&dir=desc" <?php if($sortVal == 'subscription' && $sortdirVal == 'desc'):?> selected<?php endif; ?> ><?php echo __('Aflopend met abonnement') ?></option>
                                        <option  value="sort=price&dir=desc" <?php if($sortVal == 'price' && $sortdirVal == 'desc'):?> selected<?php endif; ?> ><?php echo __('Aflopend zonder abonnement') ?></option>
                                        <option  value="sort=subscription&dir=asc" <?php if($sortVal == 'subscription' && $sortdirVal == 'asc'):?> selected<?php endif; ?> ><?php echo __('Oplopend met abonnement') ?></option>
                                        </select>
								</div>
							</div>
						</div>
					</div>
				</article>
				<div class="container">
					<?php
					$i=0;
					$j = 0;
					$_productCount = count($_productCollection);
					$_productCount = $_productCount-1;
		?>
		<?php if ($this->getRequest()->getParam('p')):?>
		<?php
			  $cur = $this->getRequest()->getParam('p') - 1;
              $j = $cur * 3;
		?>
		<?php endif;?>
		<?php
			$coloffsetdiv = 0;
			$column = 0;
		?>
		<?php foreach ($_productCollection as $_product): ?>
					<?php $column++; ?>
					<?php if ($i % 2 == 0) :?>
					<?php $j++; ?>
					<?php $coloffsetdiv++;?>
					<div class="row margin-xs-v-m item product product-item">
					<div class="col-xs-12 col-sm-5 item <?php if ($coloffsetdiv % 2 == 0):?> col-sm-offset-2<?php endif;?> product product-container <?php echo 'custom-row'.$j; ?>">
					<?php else : ?>
					<?php $coloffsetdiv++;?>
					<div class="col-xs-12 col-sm-5 item <?php if ($coloffsetdiv % 2 == 0):?> col-sm-offset-2<?php endif;?> product product-container <?php echo 'custom-row'.$j; ?>">
					<?php endif; ?>

						<?php
							$familyType = 'smartphone';
							$stockProduct = $block->getHighStockProduct($_product->getHandsetFamily(),$familyType);
							if(!$stockProduct->getId())
							{
								$stockProduct = $_product;
							}
							$tierPrice = $stockProduct->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
							$colorName  = $_catalogHelper->getColorOption($stockProduct);
							$productTitle = str_replace($colorName,"",$stockProduct->getName());
							$alt_tag = __('Orange Belgique').' - '.$productTitle.' - '.$colorName;

						?>
							<!-- Product Content -->

							<div class="media phone-item margin-xs-t-n smartphone_hgt">
							   <div class="coupon-stickk">
								<?php $standAloneCashBack = $this->getStandAloneCashBack($stockProduct);?>
								<?php if($standAloneCashBack){ ?>
										<i class="oi oi-tag"></i>&nbsp; <?php echo __('Cashback %1', $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($standAloneCashBack, 0), true, false)) ?><br>
								<?php } else {
									$promotionSticker = $this->getPromotionSticker($stockProduct);
									if($promotionSticker){ ?>
									<i class="oi oi-tag"></i>&nbsp; <?php echo __($promotionSticker); ?><br>
								<?php } } ?>
								</div>
								<div class="media-left pull-left">
									<div class="margin-xs-v-s">
										<?php
										$imageUrl = $this->helper('Magento\Catalog\Helper\Image')
											->init($stockProduct, 'intermediate_page_image_medium')
											->setImageFile($stockProduct->getFile())
											->getUrl();
											if(isset($_GET['p'])){?>
											<img src="<?php echo $imageUrl; ?>" alt = "<?php echo trim($alt_tag); ?>">
											<?php }else{
											?>
											<div id="lazy" class="lazy-load">
										<img class="lof-lazy" data-src="<?php echo $imageUrl; ?>"  alt="<?php echo trim($alt_tag); ?>"
										<?php
										$image = 'category_page_grid';
										$productImage = $block->getImage($_product, $image);
										echo $productImage->toHtml();
										?>
										</div>
										<?php	}
										?>

									</div>
								</div>
								<div class="media-body">
									<?php $handsetName = $stockProduct->getHandsetFamily();?>
									<?php if (str_word_count($handsetName)>1):?>
										<?php $arr = explode(' ',trim($handsetName));?>
										<h3 class="js-matchBoxHeight margin-xs-t-s">
										<?php echo nl2br($arr[0]."\n".substr(strstr($handsetName," "), 1));?>
										</h3>
									<?php else:?>
										<h3 class="js-matchBoxHeight margin-xs-t-s"><?php /* @escapeNotVerified */ echo __($stockProduct->getHandsetFamily()); ?></h3>
									<?php endif?>
                                    <div class="ratings">
									<?php
									$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
									$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
									//getting current store id
									 $storeCode = $storeManager->getStore()->getName();
									 if($storeCode == 'Dutch'){
									  $reevooId = 'MBD';
									 }else{
										 $reevooId = 'MBF';
									 }
									 ?>
									<reevoo-reviewable-badge trkref="<?php echo $reevooId ?>" sku="<?php echo $_product->getSku() ?>" variant="category_page"></reevoo-reviewable-badge>
                                                                         </div>
									<?php
									//$family = $deviceBlock->getDeviceFamilyText($_product); //Device family
									$familyId = $_product->getHandsetFamily();
									$availableColors = $deviceBlock->getAvailableColors($familyId);
									if($this->getCustomerTypeName()=='SOHO'):
										$deviceSubscriptionPrice = $_product->getMinSohoSubsidyPrice();
									else:
										$deviceSubscriptionPrice = $_product->getMinSubsidyPrice();
									endif;
									?>
									<?php if(count($availableColors) > 1): ?>
										<p><?php /* @escapeNotVerified */ echo __('Disponible en %1 couleurs', count($availableColors)) ?></p>
									<?php ?>
									<?php endif; ?>
									<?php if($stockProduct->getObsoleteDevice() == 1):?>
										<p class="red"><?php /* @escapeNotVerified */ echo __('Epuisé') ?></p>
									<?php else: ?>
										<?php if($stockProduct->isAvailable()): ?>
                                                <p class="green"><?php /* @escapeNotVerified */ echo __('En stock') ?></p>
										<?php else: ?>
												<p class="red"><?php /* @escapeNotVerified */ echo __('Indisponible') ?></p>
										<?php endif; ?>
									<?php endif; ?>

                                                                        <?php if($stockProduct->getObsoleteDevice() != 1):?>
                                                                            <p class="title-price"><?php /* @escapeNotVerified */ echo __('Sans abonnement') ?></p>
                                                                            <div class="clearfix"></div>
                                                                            <?php $finalPrice = $stockProduct->getPriceInfo()->getPrice('final_price')->getAmount()->getValue(); ?>
                                                                            <?php echo $block->getOrangePricingHtml($finalPrice,true,true,false,'lob new-price orange'); ?>
                                                                            <?php
                                                                            if($deviceSubscriptionPrice):
                                                                            ?>
                                                                            <p class="title-price"><?php /* @escapeNotVerified */ echo __('Avec abonnement') ?></p>
                                                                            <small class="since_text"><?php /* @escapeNotVerified */ echo __('à partir de') ?></small>
                                                                            <?php echo $block->getOrangePricingHtml($deviceSubscriptionPrice,true,true,false,'lob new-price orange'); ?>
                                                                            <?php endif; ?>
                                                                        <?php endif; ?>
									<?php $formattedUrl = $_catalogHelper->getFormattedUrl($stockProduct->getProductUrl()); ?>
									<div class="clearfix"></div>
								</div>
							</div>
							<div class="order-bttn">
								<a class="btn btn-primary margin-xs-t-m margin-xs-b-m text-center <?php if($currentStoreId == 2): ?>caddy-cta-fr<?php else:?>caddy-cta<?php endif;?>" href="<?php echo $formattedUrl; ?>"><?php /* @escapeNotVerified */ echo __("Plus d'infos") ?></a>
							</div>
						</div>
						<?php
						/** Tealium Tag Data *********/
						if($tealiumStatus){
							$udodata['product_category'][] 	= strtolower($udoBlock->getAttributesValue($stockProduct,'tealium_product_category'));
							$udodata['product_type'][] 		= strtolower($udoBlock->getAttributesValue($stockProduct,'tealium_product_type'));
							$udodata['product_brand'][] 	= strtolower($udoBlock->getAttributesValue($stockProduct,'brand'));
							$udodata['product_sku'][] 		= $stockProduct->getSku();
							$udodata['product_name'][] 		= strtolower($stockProduct->getTealiumPageName());
							$udodata['product_unit_price'][]= str_replace(",","",number_format($stockProduct->getPrice('final_price'),2));

							if ($this->getRequest()->getParam('p') &&  $column == 6): ?>
								<script type="text/javascript">
									var ajax_utag_data = <?php echo str_replace("}", "\n}",str_replace("{", "{\n    ",str_replace(",", ",\n    ", json_encode($udodata, JSON_UNESCAPED_UNICODE)))); ?>;
									var utag_keys = ['product_category', 'product_type', 'product_brand', 'product_sku', 'product_name', 'product_engagement_period', 'product_monthly_price', 'product_unit_price'];
									if (typeof ajax_utag_data == "object" && typeof utag_data == "object"){
  									for (key in ajax_utag_data) {
  										if (utag_keys.indexOf(key) >= 0) {
  											var data = temp_udo_data[key].concat(ajax_utag_data[key]);
   											temp_udo_data[key] = data;
  										}
  									}
  									utag.view(temp_udo_data);
									};
								</script>
							<?php
							endif;
						}
						/*****************************/
						?>
						<?php if ($i % 2 != 0) :?>
						</div>
						<?php endif; ?>
						<?php if($_productCount == $i && $i % 2 == 0): ?>
						</div>
						<?php endif; ?>
						<?php $i++; ?>

					<?php endforeach; ?>

					<?php if($tealiumStatus && !isset($_GET['p'])){ ?>
							<script type="text/javascript">
								var temp_udo_data = {};
								// Tealium Data Call for Landing Page //
								var utag_data = <?php echo str_replace("}", "\n}",str_replace("{", "{\n    ",str_replace(",", ",\n    ", json_encode($udodata, JSON_UNESCAPED_UNICODE)))); ?>;
								temp_udo_data = utag_data;
							</script>
					<?php } ?>
				</div>
			</section>
		</div>
	</section>
	<div class="ias-noneleft-list" style="text-align: center;"></div>
	<script type="text/javascript">
	require(['jquery','bss/ias','bss/goup','bss/lazyload'],function($){
		jQuery(window).load(function() {
	jQuery.goup({
					<?php if($this->getConfigGototop('goup_speed')):?>
						goupSpeed: '<?php echo $this->getConfigGototop("goup_speed");?>',
					<?php endif;?>
					<?php if($this->getConfigGototop('location')):?>
						location: '<?php echo $this->getConfigGototop("location");?>',
					<?php endif;?>
					<?php if($this->getConfigGototop('location_offset')):?>
						locationOffset: parseInt('<?php echo $this->getConfigGototop("location_offset");?>'),
					<?php endif;?>
					<?php if($this->getConfigGototop('bottom_offset')):?>
						bottomOffset: parseInt('<?php echo $this->getConfigGototop("bottom_offset");?>'),
					<?php endif;?>
					<?php if($this->getConfigGototop('container_size')):?>
						containerSize: parseInt('<?php echo $this->getConfigGototop("container_size");?>'),
					<?php endif;?>
					<?php if($this->getConfigGototop('container_radius')):?>
						containerRadius: parseInt('<?php echo $this->getConfigGototop("container_radius");?>'),
					<?php endif;?>
					// containerClass: 'goup-container',
					// arrowClass: 'goup-arrow',
					<?php if($this->getConfigGototop('always_visible')):?>
						alwaysVisible: true,
					<?php endif;?>
					<?php if($this->getConfigGototop('trigger')):?>
						trigger: '<?php echo $this->getConfigGototop("trigger");?>',
					<?php endif;?>
					// entry: 'slide', // "slide" or "fade"
					<?php if($this->getConfigGototop('hide_under_width')):?>
						hideUnderWidth: '<?php echo $this->getConfigGototop("hide_under_width");?>',
					<?php endif;?>
					<?php if($this->getConfigGototop('container_color')):?>
						containerColor: '#<?php echo $this->getConfigGototop("container_color");?>',
					<?php endif;?>
					<?php if($this->getConfigGototop('arrow_color')):?>
						arrowColor: '#<?php echo $this->getConfigGototop("arrow_color");?>',
					<?php endif;?>
					<?php if($this->getConfigGototop('text_hover')):?>
						title: '<?php echo $this->getConfigGototop("text_hover");?>',
					<?php endif;?>
					// titleAsText: false,
					// titleAsTextClass: 'goup-text',
					<?php if($this->getConfigGototop('zindex')):?>
						zIndex: '<?php echo $this->getConfigGototop("zindex");?>',
					<?php endif;?>
				});
				});
				});
				</script>
<?php endif; ?>
<script type="text/javascript">
	require([
		'jquery',
		'js/dropdown'
	], function ($) {
	//<![CDATA[
		$(document).on("keypress", "#sso-email", function(e) {
			 if (e.which == 13) {
				 processParams($(this));
			 }
		});
		$('#brandfilter').change(function(){
			processParams($(this));
		});
		$('#sortby').change(function(){
			//processParams($(this));
			var sort_by = $('#sortby').val();
			var brandId     = $('#brandfilter').val();
			var searchQuery = $('#sso-email').val();
			if($('#sso-email').val()!='' && brandId == "")
			{
				var params = "?search="+searchQuery+"&"+sort_by;
			}
			else if(brandId != "" && $('#sso-email').val()=='')
			{
				//has brand filter
				var params = "?brand="+brandId+"&"+sort_by;
			}
			else if($('#sso-email').val()!='' && brandId != "")
			{
				//has search and brand filter
				var params = "?search="+searchQuery+"&brand="+brandId+"&"+sort_by;
			}
			else
			{
				if(sort_by!=""){
				   var params = "?" + sort_by;
				}else{
				   var params =window.location.href.split('?')[0];
				}
			}
			window.location.href = params;
		});
        function processParams(element)
		{
			var sort_by = $('#sortby').val();
			var params = "?";
			if($('#sso-email').val()!='')
			{
				var searchQuery = $('#sso-email').val();
				var brandId     = $('#brandfilter').val();
				if(brandId != "")
				{
					if(sort_by!=""){
						var params = "?search="+searchQuery+"&brand="+brandId+"&"+sort_by;
					}
					else {
						var params = "?search="+searchQuery+"&brand="+brandId;
					}
				}
				else
				{
					if(searchQuery!='')
					{
						if(sort_by!=""){
							var params = "?search="+searchQuery+"&"+sort_by;
						}
						else {
							var params = "?search="+searchQuery;
						}
					}
					else
					{
						if(sort_by!=""){
							var params = "?search="+"&"+sort_by;
						}
						else {
							var params = "?search=";
						}
					}
				}
			}
			else if($('#brandfilter').val() != "")
			{
				var brandId = $('#brandfilter').val();
				if($('#sso-email').val()!='')
				{
					var searchQuery = $('#sso-email').val();
					if(sort_by!=""){
						var params = "?search="+searchQuery+"&brand="+brandId+"&"+sort_by;
					}
					else {
						var params = "?search="+searchQuery+"&brand="+brandId;
					}
				}
				else
				{
					if(sort_by!=""){
						var params = "?brand="+brandId+"&"+sort_by;
					}
					else {
						var params = "?brand="+brandId;
					}
				}
			}
			else if(sort_by != "")
			{
				var params = "?" + sort_by;
			}
			else {
				var params = window.location.href.split('?')[0];
			}

			window.location.href = params;
		}
		//Filter select on browser using back button
		function getParameter(theParameter) {
			var params = window.location.search.substr(1).split('&');

			for (var i = 0; i < params.length; i++) {
				var p=params[i].split('=');
				if (p[0] == theParameter) {
					return decodeURIComponent(p[1]);
				}
			}
			return false;
		}
		var brandVal = getParameter('brand');
		if(brandVal) {
			$('#brandfilter').val(brandVal);
		}
		else {
			$("#brandfilter option:first").attr('selected','selected');
		}

		var sortVal = getParameter('sort');
		var dirVal = getParameter('dir');
		if(sortVal) {
			var formatVal = 'sort='+sortVal+'&dir='+dirVal;
			$('#sortby').val(formatVal);
		}
		else {
			$("#sortby option:first").attr('selected','selected');
		}


	//]]>
	});
	require(['jquery'], function ($) {
        function tog(v) {
            return v ? 'addClass' : 'removeClass';
        }
        $(document).on('input', '.search-device', function () {
            $(this)[tog(this.value)]('x');
        }).on('mousemove', '.x', function (e) {
            $(this)[tog(this.offsetWidth - 18 < e.clientX - this.getBoundingClientRect().left)]('onX');
        }).on('touchstart click', '.onX', function (ev) {
            ev.preventDefault();
            $(this).removeClass('x onX').val('').change();
        });
    });
</script>
<script id="reevoomark-loader" type="text/javascript" charset="utf-8">
require(['jquery'], function ($) {
$(window).load(function() {
    (function (w, d, u, i, f, s, l) {
        s = d.createElement('script');
        s.type = 'text/javascript';
        s.src = u;
        l = d.getElementById(i);
        l.parentNode.insertBefore(s, l);
        w['ReevooMarkHandlerName'] = f;
        w[f] = function () {
            (w[f].q = w[f].q || []).push(arguments)
        }
    })(window, document, '//cdn.mark.reevoo.com/assets/reevoo_mark.js', 'reevoomark-loader', 'reevooMark');
	});
	});
</script>
<script type="text/javascript">
require(['jquery'], function ($) {
	function equalheight(container){
		var currentTallest = 0,
					currentRowStart = 0,
					rowDivs = new Array(),
					$el,
					topPosition = 0;

		$(container).each(function() {
			$el = $(this);
			$($el).height('auto')
			topPostion = $el.position().top;

			if (currentRowStart != topPostion) {
						for (currentDiv = 0 ; currentDiv < rowDivs.length ; currentDiv++) {
									rowDivs[currentDiv].height(currentTallest);
						}
						rowDivs.length = 0; // empty the array
						currentRowStart = topPostion;
						currentTallest = $el.height();
						rowDivs.push($el);
			} else {
						rowDivs.push($el);
						currentTallest = (currentTallest < $el.height()) ? ($el.height()) : (currentTallest);
			}
			for (currentDiv = 0 ; currentDiv < rowDivs.length ; currentDiv++) {
						rowDivs[currentDiv].height(currentTallest);
			}
		});
	}

	$(window).load(function() {
		$('.product-item').each(function(index){
					position = index + 1;
					equalheight('.custom-row'+position+' .smartphone_hgt');
		});
	});
	$(window).resize(function(){
		$('.product-item').each(function(index){
			position = index + 1;
			equalheight('.custom-row'+position+' .smartphone_hgt');
		});
	});

	$(window).scroll(function () {
		$('.product-item').each(function(index){
			position = index + 1;
			equalheight('.custom-row'+position+' .smartphone_hgt');
		});
	});

	$(window).load(function() {
		$('.smartphone-hero').each(function(index){
					equalheight('.smartphone-hero .phone-item');
		});
	});

});
</script>
