<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category    Dilmah
 * @package     Dilmah_Customer
 * @author      Netstarter Team <contact@netstarter.com>
 * @copyright   Copyright (c) 2015 Netstarter Pty Ltd. (http://www.netstarter.com.au)
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
 
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeManager->getStore()->getName() . '<br />';
?>
<div class="login-register-tab-container">
    <div class="tab-login active">
        <?php /* @escapeNotVerified */ echo __('Returing Customers') ?>
    </div>
    <div class="tab-register">
        <a href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>"><?php /* @escapeNotVerified */ echo __('New Customers') ?></a>
    </div>
</div>
<div class="block block-customer-login">
    <div class="login-form-section">
        <div class="block-title">
            <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Login') ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form form-login"
                  action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
                  method="post"
                  id="login-form"
                  data-mage-init='{"validation":{}}'>
                <?php echo $block->getBlockHtml('formkey'); ?>
                <fieldset class="fieldset login"">
                <div class="field email required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email address') ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                    <?php if($storeManager->getStore()->getName() == "FR"):?><label style="color: #666;font-family: 'signika_regular';font-size: 1.6rem;margin-bottom: 10px;display: block;"><?php /* @escapeNotVerified */ echo __('Le mot de passe doit contenir au moins 8 caractères, et utiliser au moins 1 majuscule, 1 minuscule et 1 chiffre ou caractère spécial') ?></span></label><?php endif;?>
					<div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button></div>
                    <div class="sign-up"><a class="sign-link" href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>"><?php /* @escapeNotVerified */ echo __('Sign up') ?></a></div>
                    <div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a></div>
                </div>
                </fieldset>
            </form>
        </div>
        <div class="fb-button-section">
            <span><?php /* @escapeNotVerified */ echo __('or') ?></span>
            <?php echo $this->getChildHtml('header.links.FbButton.login') ?>
        </div>
    </div>
    <div class="login-info-section">
        <div class="info-wrapper">
            <?php /* @escapeNotVerified */ echo $block->getChildHtml('login.page.info') ?>
        </div>
        <div class="actions-toolbar">
            <div class="sign-up-now"><a href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>"><?php /* @escapeNotVerified */ echo __('Sign up now') ?></a></div>
        </div>
    </div>
</div>
