<?php
/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Scommerce\Gdpr\Block\Account\Deletion $block
 */
?>

<div class="block">
    <div class="block-content">
        <p class="scommerce-gdpr-attention-message"><?php echo $block->getAttentionMessage() ?></p>
        <br>
        <button id="js-scommerce-gdpr-delete-button" type="button" title="<?php echo __('Delete my account') ?>" class="button">
            <span><?php echo __('Delete my account') ?></span>
        </button>
    </div>
</div>

<script>
    require([
        'jquery'
    ], function($) {
        $('#js-scommerce-gdpr-delete-button').on('click', function(e) {
            e.preventDefault();
            window.location.href = "<?php echo $block->getDeleteUrl() ?>";
        });
    });
</script>
