<?php
/**
 *
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Orange\SalesRule\Controller\Adminhtml\Promo\Quote;

class ImportCoupon extends \Magento\SalesRule\Controller\Adminhtml\Promo\Quote
{
    /**
     * Import Coupons action
     *
     * @return void
     */
    public function execute()
    {	        
        $this->_initRule();

        /** @var $rule \Magento\SalesRule\Model\Rule */
        $rule = $this->_coreRegistry->registry(\Magento\SalesRule\Model\RegistryConstants::CURRENT_SALES_RULE);
		echo 'rule id:'.$this->getRequest()->getParam('rule_id');
        if (!$rule->getId()) {
			$this->messageManager->addError('Rule is not defined');
        } else {
            try {
				$data = $this->getRequest()->getPostValue();            
				if (isset($_FILES["importcoupondata"])) {
					$filename = $_FILES["importcoupondata"]["name"];
					$source   = $_FILES["importcoupondata"]["tmp_name"];
					$type     = $_FILES["importcoupondata"]["type"];
					$name     = explode(".", $filename);
					$mimes    = array(
						'application/vnd.ms-excel',
						'text/csv'
					);
					if (in_array($_FILES['importcoupondata']['type'], $mimes)) {
						$all_rows = array();
						$header   = null;
						$fh       = fopen($_FILES['importcoupondata']['tmp_name'], 'r+');
						while ($row = fgetcsv($fh, 8192)) {
							if ($header === null) {
								$header = $row;
								continue;
							}
							$all_rows = array_combine($header, $row);
							$this->generateCouponCode($all_rows);
						}
						$this->messageManager->addSuccess('Coupons Imported Successfully.');
					} else {
						$this->messageManager->addError('Wrong File Type. Please insert CSV format file..');
					}
				}				
            } catch (\Magento\Framework\Exception\LocalizedException $e) {                
				$this->messageManager->addError($e->getMessage());
            } catch (\Exception $e) {
                $errormsg ='Something went wrong while generating coupons. Please review the log and try again.';
				$this->messageManager->addError($errormsg);
                $this->_objectManager->get('Psr\Log\LoggerInterface')->critical($e);
            }
        }
    }
	
	private function generateCouponCode($couponData)
	{		
		$couponCode = $couponData['Coupon Code'];
		$createdAt = $couponData['Created'];
		$timesUsed = $couponData['Uses']; // Need to confirm what data it is
		$usageLimit = $couponData['Times Used'];				
		$coupon = $this->_objectManager->get('Magento\SalesRule\Model\CouponFactory')->create();
		$coupon->setId(null);
		$coupon->setRuleId($this->getRequest()->getParam('rule_id'));
		$coupon->setUsageLimit(1);
		$coupon->setUsagePerCustomer(1);
		$coupon->setTimesUsed($timesUsed);
		$coupon->setExpirationDate(date("Y-m-d H:i:s"));
		$coupon->setCreatedAt(date('Y-m-d h:m:s',strtotime($createdAt)));
		$coupon->setType(\Magento\SalesRule\Helper\Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED);
		$coupon->setCode($couponCode);
		$coupon->save();
	}
}
