<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$upsellProducts = $this->getUpsellProducts();
$no_of_count    = count($upsellProducts);

?>

<?php if($product->getTypeId() == 'bundle') { ?>
<div class="row"><div class="col-xs-12 col-sm-12 col-md-12">
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('conditions_nintendo')->toHtml(); ?>
</div>
</div>
<?php } else { if($upsellProducts && $no_of_count !=0) { ?>
<div class="row"><div class="col-xs-12 col-sm-12 col-md-12">
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('conditions_nintendo')->toHtml(); ?>
</div>
</div>
<?php } } ?>
