<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$_count = $block->getCollectionSize();
?>

<div class="write-review"><a href="#"><?php echo __('Write a review') ?></a></div>

<?php echo $block->getChildHtml(); ?>
<div id="product-review-container" data-role="product-review"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?php /* @escapeNotVerified */ echo $block->getProductReviewUrl();?>"
            }
        }
    }
</script>