<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Dilmah\Checkout\Block\Onepage\Success */ ?>
<?php
if ($block->isCustomerLoggedIn()) {
    $firstName = $this->getCheckoutSession()->getQuote()->getCustomer()->getFirstname();
} else {
    $firstName = $block->getCheckoutSession()->getLastRealOrder()->getBillingAddress()->getFirstname();
}
?>
<div class="thank-you"><?php echo __('Thanks for your purchase %1', $firstName); ?></div>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
        <p><?php echo __('Je bestelnummer is %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
    <?php  else :?>
        <p><?php echo __('Je bestelnummer is <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
    <?php endif;?>
        <?php $order = $block->getCheckoutSession()->getLastRealOrder(); ?>
        <p><?php /* @escapeNotVerified */ echo __('Your order is processing. You will receive a confirmation by email soon.') ?></p>
        <?php echo $block->getVirtualProductMessage($order); ?>
        <?php
        $printUrl = null;
        if ($block->isCustomerLoggedIn()) {
            $printUrl = $this->getUrl('sales/order/print', ['order_id' => $order->getId()]);
        } else {
            //below cookie is set to avoid displaying 'order and invoice' form intead of print order page
            $block->setGuestPrintCookie($order);
            $printUrl = $this->getUrl('sales/guest/print', ['order_id' => $order->getId()]);
        }
        if ($printUrl):
        ?>
        <a class="action print"
           href="<?php /* @escapeNotVerified */ echo $printUrl ?>"
           onclick="this.target='_blank';">
            <span><?php /* @escapeNotVerified */ echo __('Print Order ') ?></span>
        </a>
    <?php endif;
        endif;?>
    <?php echo $block->getAdditionalInfoHtml(); ?>
</div>
