<?php
/**
 * @var \Scommerce\Gdpr\Block\Form\Subscribe $block
 */
?>

<div class="field choice scommerce_gdpr_privacy_consent_newsletter">
    <input type="checkbox" name="scommerce_gdpr_privacy_consent" value="1" id="scommerce_gdpr_privacy_consent" class="checkbox" data-validate="{required:true}" />
    <label for="scommerce_gdpr_privacy_consent" class="label"><?php echo $block->getPrivacySettingText() ?></label>
</div>
