<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category    Dilmah
 * @package     Dilmah_Theme
 * @author      Netstarter Team <contact@netstarter.com>
 * @copyright   Copyright (c) 2015 Netstarter Pty Ltd. (http://www.netstarter.com.au)
 */

// @codingStandardsIgnoreFile

?>
<div class="bottom-newsletter-slider-content">
    <a href="#" class="close-icon">
        <span class="icon-close"></span>
    </a>
    <p class="content-header"><?php echo __('Get Specials & Get Rewarded') ?></p>
    <span class="content-sub"><?php echo __('by subscribing to our newsletters!') ?></span>
    <?php echo $block->getChildHtml('newsletter.content'); ?>
</div>