<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category    Dilmah
 * @package     Dilmah_Catalog
 * @author      Netstarter Team <contact@netstarter.com>
 * @copyright   Copyright (c) 2015 Netstarter Pty Ltd. (http://www.netstarter.com.au)
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;

$ordered = array();
$orderArray = array('top_rated','name','price');
$array=$block->getAvailableOrders();
foreach($orderArray as $key) {
    if(array_key_exists($key,$array)) {
        $ordered[$key] = $array[$key];
        unset($array[$key]);
    }
}
$availableOrders = $ordered + $array;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?php /* @escapeNotVerified */ echo __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options custom">
        <?php
        foreach ($availableOrders as $_key => $_order):
            switch($_key):
                case 'price':
                ?>
                    <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                        <?php if ($block->isOrderCurrent($_key) && $block->getCurrentDirection()=='asc'): ?>
                            selected="selected"
                        <?php endif; ?>
                            data-role="direction-switcher" data-value="asc"
                        >
                    <?php echo __('Price: Low to High'); //$block->escapeHtml(__($_order)) ?>
                    </option>
                    <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                        <?php if ($block->isOrderCurrent($_key) && $block->getCurrentDirection()=='desc'): ?>
                            selected="selected"
                        <?php endif; ?>
                            data-role="direction-switcher" data-value="desc"
                        >
                        <?php echo __('Price: High to Low'); //$block->escapeHtml(__($_order)) ?>
                    </option>
                    <?php
                    break;

                case 'name':
                ?>
                    <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                        <?php if ($block->isOrderCurrent($_key) && $block->getCurrentDirection()=='asc'): ?>
                            selected="selected"
                        <?php endif; ?>
                            data-role="direction-switcher" data-value="asc"
                    >
                        <?php echo __('A-Z'); //$block->escapeHtml(__($_order)) ?>
                    </option>
                    <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                        <?php if ($block->isOrderCurrent($_key) && $block->getCurrentDirection()=='desc'): ?>
                            selected="selected"
                        <?php endif; ?>
                            data-role="direction-switcher" data-value="desc"
                    >
                        <?php echo __('Z-A'); //$block->escapeHtml(__($_order)) ?>
                    </option>
                <?php
                    break;

                default:
                        ?>
                        <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                            <?php if ($block->isOrderCurrent($_key)): ?>
                                selected="selected"
                            <?php endif; ?>
                                data-role="direction-switcher" <?php if($_key =='top_rated'):?> data-value="desc" <?php else: ?> data-value="asc"<?php endif; ?>
                        >
                            <?php echo $block->escapeHtml(__($_order)) ?>
                        </option>
            <?php endswitch;
        endforeach; ?>
    </select>
</div>
