<?php

use Magento\Framework\App\TemplateTypesInterface;

$url = $block->getSaveUrl();
$reIndexurl = $block->getReindexUrl();
?>

<form enctype="multipart/form-data" id="subsidy_price" name="subsidy_price-footer" method="post" action="<?php echo $url; ?>">
    <br />
    <div id="uploader"> 
        <label class="label admin__field-label" for="csv_file" data-validate="{required:true}"> 
            <span>Upload CSV file: </span>
        </label>
        <input type="file" name="csv_file" data-validate="{required:true}"/>
    </div>
    <br />
    <input class="action-default scalable task" type="submit" name="submit" value="Import" />
</form>

<br>
<br>

<form id="reindex-all" name="reindex-all" method="post" action="<?php echo $reIndexurl; ?>">
    <input class="action-default scalable task" type="submit" name="reindex" value="Reindexing" />
</form>

<script type="text/x-magento-init">
    {
    "#subsidy_price": { "validation": {}
    }
    }
</script>