<script type="text/x-magento-init">
    {
        ".news-articles" : {
            "newsEvents": {}
        }
    }
</script>
<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category    Dilmah
 * @package     Dilmah_NewsEvents
 * @author      Netstarter Team <contact@netstarter.com>
 * @copyright   Copyright (c) 2015 Netstarter Pty Ltd. (http://www.netstarter.com.au)
 */

/** @var \Dilmah\NewsEvents\Block\NewsAndEvents $block */

echo $block->getNewsItems('full');