<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */
?>
<?php $_product = $block->getProduct() ?>
<?php $isCombo = $_product->getData(\Dilmah\Catalog\Helper\Data::IS_COMBO_PRODUCT_ATTRIBUTE) == 1 ?>
<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($isCombo): // mix and match products need only the out of stock message ?>
        <?php if (!$_product->isAvailable()): ?>
            <p class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability:') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
            </p>
        <?php endif; ?>
    <?php else: ?>
        <?php if ($_product->isAvailable()): ?>
            <p class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability:') ?>">
                <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
            </p>
        <?php else: ?>
            <p class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability:') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
            </p>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
<?php echo $block->getChildHtml('bundle_prices') ?>
