<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category    Dilmah
 * @package     Dilmah_ProductSlider
 * @author      Netstarter Team <contact@netstarter.com>
 * @copyright   Copyright (c) 2015 Netstarter Pty Ltd. (http://www.netstarter.com.au)
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Dilmah\ProductSlider\Block\Widget\ProductWidget
 */
$productCollection = $block->getProductCollection();
if ($productCollection && $productCollection->getSize()):
    $type = 'widget-new-grid';

    $mode = 'grid';

    $imageBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
    $image = 'new_products_content_widget_grid';
    $title = __($block->getData('captions'));
    $items = $block->getProductCollection()->getItems();

    $showWishlist = false;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="product-slider-wrapper">
        <div class="block-new-products <?php echo $mode; ?>">
            <div class="block-title">
                <h2 role="heading" aria-level="2"><?php echo $title; ?></h2>
            </div>
            <div class="block-content">
                <?php echo '<!-- ' . $image . '-->' ?>
                <div class="products-<?php echo $mode; ?> <?php echo $mode; ?>">
                    <div data-mage-init='{"productSlider":{"desktopLength":4,"tabLength":3, "mobileLength":2}}'
                         class="product-slider-carousel product-items <?php echo $type; ?>">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                            <?php echo ($iterator++ == 1) ? '<div class="product-item">'
                                : '</div><div class="product-item">' ?>
                            <div class="product-item-info">
                                <?php
                                $productImage = $block->getImage($_item, $image);
                                ?>
                                <?php // Product Image ?>
                                <a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?php echo $productImage->toHtml(); ?>
                                </a>

                                <div class="product-item-details">
                                    <ul class="tags">
                                        <?php if ($_item->getData(\Dilmah\Catalog\Helper\Data::LABEL_MANAGER_SALE_ATTRIBUTE)): ?>
                                            <li class="sale">Sale</li>
                                        <?php endif; ?>
                                        <?php if ($_item->getData(\Dilmah\Catalog\Helper\Data::LABEL_MANAGER_NEW_ATTRIBUTE)): ?>
                                            <li class="new">New</li>
                                        <?php endif; ?>
                                        <?php if ($_item->getData(\Dilmah\Catalog\Helper\Data::LABEL_MANAGER_PROMO_ATTRIBUTE)): ?>
                                            <li class="promo">Promo</li>
                                        <?php endif; ?>
                                    </ul>
                                    <strong class="product-item-name">
                                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                           href="<?php echo $block->getProductUrl($_item) ?>"
                                           class="product-item-link">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                    <ul class="pack-desc">
                                        <?php if ($_item->getData(\Dilmah\Catalog\Helper\Data::IS_PACK_PRODUCT_ATTRIBUTE) == 1): // if pack product ?>
                                            <?php if ($packSize = $_item->getData(\Dilmah\Catalog\Helper\Data::PACK_SIZE_ATTRIBUTE)): ?>
                                                <li class="packs"><?php echo sprintf(__('Pack of %s'), $packSize) ?></li>
                                                <?php if ($bags = $_item->getData(\Dilmah\Catalog\Helper\Data::TEA_BAG_QTY_ATTRIBUTE)): ?>
                                                    <li class="bags"><?php echo sprintf(__('%s Tea bags'), $packSize * $bags) ?></li>
                                                <?php elseif ($grammage = $_item->getData(\Dilmah\Catalog\Helper\Data::GRAMMAGE_ATTRIBUTE)): ?>
                                                    <li class="grammage"><?php echo sprintf(__('%s Grams'), $packSize * $grammage) ?></li>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </ul>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                                    <div class="<?php echo ($_item->getMixAndMatchPromotion() ? 'mix-and-match-product' : '')?>">
                                        <?php echo $block->getProductPriceHtml($_item, $type);?>
                                    </div>
                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if ($_item->getTypeInstance()
                                                            ->hasRequiredOptions($_item)
                                                        ): ?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                    type="button"
                                                                    title="<?php echo __('Add to Cart') ?>">
                                                                <span><?php echo __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            <?php
                                                            $postDataHelper
                                                                = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData
                                                                = $postDataHelper->getPostData($block->getAddToCartUrl($_item),
                                                                ['product' => $_item->getEntityId()])
                                                            ?>
                                                            <button class="action tocart primary"
                                                                    data-post='<?php echo $postData; ?>'
                                                                    type="button"
                                                                    title="<?php echo __('Add to Cart') ?>">
                                                                <span><?php echo __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <div class="stock unavailable">
                                                            <span><?php echo __('Out of stock') ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()
                                                        && $showWishlist
                                                    ): ?>
                                                        <a href="#"
                                                           data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?php echo __('Add to Wish List') ?>">
                                                            <span><?php echo __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php $compareHelper
                                                            = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                        <a href="#" class="action tocompare"
                                                           data-post='<?php echo $compareHelper->getPostDataParams($_item); ?>'
                                                           title="<?php echo __('Add to Compare') ?>">
                                                            <span><?php echo __('Add to Compare') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php echo ($iterator == count($items) + 1) ? '</div>' : '' ?>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
