<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category    Netstarter
 * @package     Netstarter_StackFaq
 * @author      Netstarter Team <contact@netstarter.com>
 * @copyright   Copyright (c) 2016 Netstarter Pty Ltd. (http://www.netstarter.com.au)
 */

// @codingStandardsIgnoreFile
?>
<div class="faq-menu faq-top-links">
    <a href="/tea-faq/" class="faq active" alt="Tea FAQ" title="<?php /* @escapeNotVerified */ echo __('Tea FAQ') ?>"><?php /* @escapeNotVerified */ echo __('Tea FAQ') ?></a>
    <a href="/faq/" class="faq" alt="Store FAQ" title="<?php /* @escapeNotVerified */ echo __('Store FAQ') ?>"><?php /* @escapeNotVerified */ echo __('Store FAQ') ?></a>
</div>