<div class="col-xs-12 col-sm-8">
	<div class="well-grey well-grey-padded margin-xs-t-m">
		<a href="" class="bin-icon"><i class="oi oi-delete"></i></a>
		<!-- <a href="" class="edit-icon"><i class="oi oi-pencil"></i></a> -->
		<div class="row margin-xs-b-m">
			<div class="col-xs-12 col-md-8">
				<h2 class="pull-left margin-xs-v-n margin-xs-r-s"><i class="oi oi-panthere"></i></h2>
				<small>Abonnement</small>
				<h4>Panthere 75</h4>
				<div class="clear"></div>
			</div>
			<div class="col-xs-12 col-md-4 padding-xs-b-s">
				<span class="new-price orange line-100percent">75€ <small>/mois</small></span>
			</div>
			<div class="clear"></div>
			<div class="col-xs-12 col-sm-6">
				<p>
					N°: 0474 23 76 99
				</p>
			</div>
		</div>

		<div class="separator">
			<div class="plus-box-grey">
				<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-12 col-md-8">
				<h2 class="pull-left margin-xs-t-s margin-xs-r-s"><i class="oi oi-smartphone"></i></h2>
				<h4>Apple Iphone 6 gris <br class="hidden-xs">sidéral 16 GB</h4>
				<div class="clear"></div>
			</div>
			<div class="col-xs-12 col-md-4 padding-xs-b-s">
				<span class="new-price orange line-100percent">199€ <small>/mois</small></span>
			</div>
			<div class="clear"></div>
		</div>				
	</div>

	<div class="container-grey margin-xs-t-m">
		<div class="row">
			<div class="col-xs-12 col-sm-8 col-md-9">
				<input class="form-control" autocomplete="off" type="text" name="USER" id="sso-email" placeholder="Code promo">
			</div>
			<div class="col-xs-12 col-sm-4 col-md-3 margin-xs-t-s margin-sm-t-n">
				<a class="btn btn-primary" href="">Je valide</a>
			</div>
		</div>
	</div>
</div>
<div class="col-xs-12 col-sm-4">					
	<div class="container-black margin-xs-t-n margin-sm-t-m">
		<div class="row">
			<div class="col-xs-12">
				<h3 class="margin-xs-t-n margin-xs-b-m">Total</h3>
			</div>
			<div class="col-xs-12">
				<div class="row margin-xs-b-s">
					<div class="col-xs-8 col-md-7">
						Je paie chaque mois
					</div>
					<div class="col-xs-4 col-md-5 text-right">
						<span class="new-price-smaller orange line-100percent">107€</span>
					</div>
				</div>
				<div class="row margin-xs-b-s">
					<div class="col-xs-8 col-md-7">
						Je paie a la commande
					</div>
					<div class="col-xs-4 col-md-5 text-right">
						<span class="new-price-smaller orange line-100percent">199€</span>
					</div>
				</div>
				<div class="row margin-xs-b-s">
					<div class="col-xs-8 col-md-7">
						Livraison
					</div>
					<div class="col-xs-4 col-md-5 text-right">
						<span class="new-price-smaller orange"><small>Gratuite</small></span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
