<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Dilmah\Seo\Block\ListJson $block */
$product = $block->getCurrentProduct();
?>

<script>
    dataLayer.push({
        'event' : 'productDetail',
        'ecommerce': {
            'detail': {
                'actionField': {
                    'list':"<?php /* @escapeNotVerified */ echo $block->escapeJsQuote($block->getCurrentCategory()->getName()); ?>"
                },
                'products': [{
                    'id': "<?php /* @escapeNotVerified */ echo $block->escapeJsQuote($product->getSku()); ?>",
                    'name': "<?php /* @escapeNotVerified */ echo $block->escapeJsQuote($product->getName()); ?>",
                    'price': "<?php /* @escapeNotVerified */ echo $block->escapeJsQuote($block->getDisplayPrice($product)); ?>",
                    'brand': "<?php /* @escapeNotVerified */ echo \Dilmah\Catalog\Helper\Data::BRAND_LABEL; ?>",
                    'category': "<?php /* @escapeNotVerified */ echo$block->escapeJsQuote($block->getCurrentCategoryName()); ?>",
                    "variant": "<?php /* @escapeNotVerified */ echo $block->escapeJsQuote($block->getProductVariant($product)); ?>"
                }]
            }
        }
    });
</script>
