<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Radio */ ?>
<?php $_option = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>
<?php
$product = $block->getProduct();
$isCombo = $product->getData(\Dilmah\Catalog\Helper\Data::IS_COMBO_PRODUCT_ATTRIBUTE) == 1;
$isPack = $product->getData(\Dilmah\Catalog\Helper\Data::IS_PACK_PRODUCT_ATTRIBUTE) == 1;
?>

<div class="field option <?php echo ($_option->getRequired()) ? ' required': ''; ?>">
    <?php if (!$isCombo && !$isPack): ?>
        <label class="label option-select-heading">
            <span><?php echo __('Please select one from the below options and click on add to cart ') ?></span>
        </label>
    <?php endif; ?>
    <div class="control">
        <div for="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]" generated="true" class="mage-error" id="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]-error" style="display: none;"></div>
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selections[0]) ?>
                <input type="hidden"
                       id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"
                       class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                       name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                       value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>" />
            <?php else:?>
                <?php if (!$_option->getRequired()): ?>
                    <div class="checkbox-bundle"></div>
                    <div class="field choice">
                        <input type="radio"
                               class="radio product bundle option"
                               id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                               name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                               <?php echo ($_default && $_default->isSalable())?'':' checked="checked" ' ?>
                               value=""/>
                        <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
                            <span><?php /* @escapeNotVerified */ echo __('None') ?></span>
                        </label>
                        <span></span>
                    </div>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <div class="field choice">
                        <div class="radio-option-wrap">


                            <input type="radio"
                               class="radio product bundle option change-container-classname"
                               id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                               <?php if ($_option->getRequired()) echo 'data-validate="{\'validate-one-required-by-name\':true}"'?>
                               name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                               <?php if ($block->isSelected($_selection)) echo ' checked="checked"' ?>
                               <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>
                               value="<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"/>
                        <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"><span></span></label>
                        <span></span>
                        </div>
                    <?php if (!$isCombo): ?>
                        <div class="bundle-option-wrap"><?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selection) ?></div>
                    <?php endif; ?>
                    </div>
                    <?php if ($isCombo): ?>
                        <div class="bundle-option-wrap"><?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selection) ?></div>
                    <?php endif; ?>

                <?php endforeach; ?>
                <div class="bundle-option-container" id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></div>
            <?php endif; ?>
            <?php if ($isCombo): ?>
            <div class="field qty qty-holder" data-mage-init='{"cartCount":{}}'>

            <!--                <label class="label" for="bundle-option---><?php ///* @escapeNotVerified */ echo $_option->getId() ?><!---qty-input">-->
<!--                    <span>--><?php ///* @escapeNotVerified */ echo __('Quantity') ?><!--</span>-->
<!--                </label>-->
                <div class="control">
                    <div class="qty-minus qty-btn">-</div>
                    <input <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?>
                           id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input"
                           class="prevent-btn input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>"
                           type="number"
                           name="bundle_option_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           value="<?php /* @escapeNotVerified */ echo $_defaultQty ?>"/>
                    <div class="qty-plus  qty-btn">+</div>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<script>
 require(['jquery', 'jquery/ui'], function($){ 

 $(".prevent-btn").keypress(function (evt) {
    evt.preventDefault();
});

 });
</script>


