<?php $om = \Magento\Framework\App\ObjectManager::getInstance(); ?>
<?php $store = $om->get('Magento\Store\Model\StoreManagerInterface'); ?>
<?php $storeId = $store->getDefaultStoreView()->getStoreId(); ?>
<?php 
 $customViewBlock = $block->getLayout()->createBlock('Orange\Catalog\Block\Product\CustomView');
 $pid = $this->getRequest()->getParam('id'); 
 $mediaUrl = $store->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).'catalog/product';
 $virtualImageUrl = '';
 $simpleProductImageUrl = '';
 $duration = 24;
 $virtualData = '';
 $simpleProductdata = '';
 $simpleName = '';
 $virtualName = '';
 if($pid) { 
  $bundleTier = $this->helper('Orange\Bundle\Helper\Data')->getBundleTierPrice($pid); 
  $bundlefinalPrice = $bundleTier[0]['final_price'];
  $virtualData = $this->helper('Orange\Bundle\Helper\Data')->VirtualProductInfo($pid); 
  if ($virtualData) {
	$subscriptionamount = $virtualData->getSubscriptionAmount();
	$virtualImageUrl = $virtualData->getImage();
	if ($virtualData->getSubsidyDuration()) {
		$duration = $virtualData->getSubsidyDuration();
	}
	$virtualName = $virtualData->getName();
  }
  
    $simpleProductdata = $this->helper('Orange\Bundle\Helper\Data')->SimpleProductInfo($pid);
	$remainingprice = $simpleProductdata->getPrice() - $bundlefinalPrice;
    $withoutdicountprice = $simpleProductdata->getPrice();
	$monthlyprice = ($withoutdicountprice - $bundlefinalPrice) - (($withoutdicountprice - $bundlefinalPrice) * ($subscriptionamount/$duration));
	if ($simpleProductdata) {
		$simpleProductImageUrl = $simpleProductdata->getImage();
	}
	 $simpleName = $simpleProductdata->getName();
 }
 ?>
 <?php if (!$virtualData || !$simpleProductdata):?>
	<?php echo __("Data is not valid"); ?>
 <?php else:?>
 
 

 
 <div class="main-container">	

	<section>
		<div class="container">
			

			<div class="row">
				
				<div class="col-xs-12 col-sm-12">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('amortissement_top')->toHtml(); ?>
				
				</div>

			</div>
<br><br>			
			<div class="row text-center">
				<div class="col-sm-5 amoz-img-div">
				     <img src='<?php echo $mediaUrl.$virtualImageUrl;?>' >
					<h4><?php echo $virtualName; ?></h4>
				     
				</div>
				<div class="col-sm-2 plus-symbol">
					+
				</div>
				<div class="col-sm-5 amoz-img-div">
				   
				   <img src='<?php echo $mediaUrl.$simpleProductImageUrl;?>' >
					<h4><?php echo $simpleName; ?></h4>
					
				</div>
			</div>
			<div class="clearfix"></div>
			<br>
			<div class="row">
				<div class="col-sm-offset-4 col-xs-12 col-sm-5">
					<div class="col-xs-12">
						<div class="col-xs-5">
						<h4><?php echo __("Mois"); ?></h4>
							
						</div>
						<div class="col-xs-7">
						<h4><?php echo __("Paiement"); ?></h4>
						</div>
					</div>
					 <?php for($i=1;$i<=$duration; $i++) {
						  $showingprice = ($withoutdicountprice - $bundlefinalPrice) - (($withoutdicountprice - $bundlefinalPrice) * ($i/$duration)); ?>
					<div class="col-xs-12">
						<div class="col-xs-5">
						<p class="amoz-price-label"><?php echo $i;?></p>							
						</div>
						<div class="col-xs-7">
						<p class="orange amoz-price"><?php echo $customViewBlock->getOrangePricingHtml($showingprice,true,true,false,'orange new-price '); ?>
					<!--	<span class="amoz-price-desimal">.74</span>
						<span class="amoz-price-symbol-desimal">€</span> --></p>
						</div>
					</div>
					<?php  } ?>
					
				</div>
				
			</div>
		</div>
	</section>

	 <?php endif;?>

</div>