<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url1 = $storeManager->getStore()->getBaseUrl();
$url = $url1 . "/checkout/cart/add/";
?>

<form enctype="multipart/form-data" id="add_virtual_product" name="add_virtual_product" method="get" action="<?php echo $url; ?>">    
    <label class="label" data-validate="{required:true}"> Enter SKU: </label>
    <input type="text" name="sku" id="sku" class="sku_data"data-validate="{required:true}"><br>

    <input class="action-default scalable task" type="submit" value="submit"/>
</form>



<script type="text/x-magento-init">
    {
    "#add_virtual_product": { "validation": {}
    }
    }
</script>

<style>
    .sku_data{
        width: 20% !important;
    }

</style>

