<?php
/**
 * Delete Email Template
 * Email template to send email deletion confirmation to customers after successfully deleting their account
 */
?>

<!--@subject Account Deletion @-->

{{template config_path="design/email/header_template"}}

<h2>Based on your request we have now successfully deleted or anonymised your personal data from our website. In case of any query or concern please feel free to get in touch with us. Thanks</h2>

{{template config_path="design/email/footer_template"}}
