<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category    Dilmah
 * @package     Dilmah_Checkout
 * @author      Netstarter Team <contact@netstarter.com>
 * @copyright   Copyright (c) 2015 Netstarter Pty Ltd. (http://www.netstarter.com.au)
 */

?>
<div class="cart-banner-desktop">
<?php echo $block->getChildHtml('banner'); ?>
</div>
<div class="cart-banner-mobile">
    <?php echo $block->getChildHtml('banner.mobile'); ?>
</div>


