<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product = $block->getProduct();
$buttonTitle = __('Add to Cart');
$isCombo = $_product->getData(\Dilmah\Catalog\Helper\Data::IS_COMBO_PRODUCT_ATTRIBUTE) == 1;
$isPack = $_product->getData(\Dilmah\Catalog\Helper\Data::IS_PACK_PRODUCT_ATTRIBUTE) == 1;
$packSize = $_product->getData(\Dilmah\Catalog\Helper\Data::PACK_SIZE_ATTRIBUTE);
?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity() && !$isCombo): ?>
            <div class="field qty" data-mage-init='{"cartCount":{}}'>
                <div class="control">
                    <?php if ($isPack && $packSize > 0): ?>
                        <select name="qty" id="mobile-qty" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text select" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>">
                            <?php for($x = 1; $x <= 6; $x++): ?>
                                <option value="<?php /* @escapeNotVerified */ echo $x ?>" <?php /* @escapeNotVerified */ echo ($block->getProductDefaultQty() * 1 == $x) ? 'selected="selected"' : '' ?>><?php /* @escapeNotVerified */ echo __('%1 unit (%2 packs)', $x, $x * $packSize) ?></option>
                            <?php endfor; ?>
                        </select>
                    <?php else: ?>
                        <div class="qty-minus mobile-qty-click">-</div>
                        <input type="number"
                               name="qty"
                               id="mobile-qty"
                               maxlength="12"
                               value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                               title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                            />
                        <div class="qty-plus mobile-qty-click">+</div>
                    <?php endif; ?>
                </div>
            </div>
            <?php endif; ?>
            <div class="actions <?php echo $isCombo ? 'wide' : '' ?>">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="mobile-product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>