<?php $upsellProducts = $this->getUpsellProducts();?> <?php if ($upsellProducts) { ?> <div class="col-xs-12 col-sm-5"><div><h1 class="js-matchBoxHeight margin-xs-t-s" ><?php echo $block->getProduct()->getName() ?></h1></div><?php } else { ?> <div><h1 class="js-matchBoxHeight margin-xs-t-s" ><?php echo $block->getProduct()->getName() ?></h1></div><div class="col-xs-12 col-sm-5"><?php } ?> 
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface'); 
$storeCode = $storeManager->getStore()->getName(); 
if ($storeCode == 'Dutch') { $reevooId = 'MBD'; } else { $reevooId = 'MBF'; } 
?>
<div class="ratings-<?php echo $storeCode;?>">
<div class="ratings ratings-scroll">
 <reevoo-reviewable-badge trkref="<?php echo $reevooId ?>" sku="<?php echo $block->getProduct()->getSku() ?>" reevoo-click-action="no_action" ></reevoo-reviewable-badge></div>
 </div>
<?php
/**
 * @Defect 5514
 * Clicking on Reevoo badge doesn't work when second or third image is
 * selected
 * @Author - Ravikant M
 * @Date - 27/11/2017
 */
 echo $block->getChildHtml('product.info.media.image'); ?></div><script id="reevoomark-loader" type="text/javascript" charset="utf-8">
	require(['jquery'], function($) {
		$(window).load(function() {
			(function (w, d, u, i, f, s, l) {
				s = d.createElement('script');
				s.type = 'text/javascript';
				s.src = u;
				l = d.getElementById(i);
				l.parentNode.insertBefore(s, l);
				w['ReevooMarkHandlerName'] = f;
				w[f] = function () {
					(w[f].q = w[f].q || []).push(arguments)
				}
			})(window, document, '//cdn.mark.reevoo.com/assets/reevoo_mark.js', 'reevoomark-loader', 'reevooMark');
		});
	});</script><script>				
	require(['jquery'], function($) {
		$(window).load(function() {
			$(".ratings").click(function( event ) {
				 
				$('.nav-tabs a[href="#' + 'tab3' + '"]').tab('show');
                if(!$("#head-collapse-tab3 > .panel-title").hasClass('open')) 
                { 
                    $('#head-collapse-tab3 > .panel-title').trigger('click');
                }
				 if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
	
	
	
                        $('html,body').animate({
                        scrollTop:$("#head-collapse-tab3").offset().top - 50},
                        'slow');
				} else {
					$('html,body').animate({
	       				scrollTop: $(".ratings-scroll").offset().top},
	        			'slow');
				}
			});
		});
         $(document).ready(function(){  
              setTimeout(function() {
				var divtext    = $.trim($(".ratings").text());
				if(divtext != ''){
					var arr 		= divtext.split('(');
				if(arr[1] != ''){
					var arr1 		= arr[1].split(')');
					if(arr1[0] != ''){
					var arr2 		= arr1[0].split(' ');
					var reviewlenth = arr2[0].length;
					if(reviewlenth == 1){
						$(".ratings").addClass('ratings-one');
						$(".ratings").removeClass('ratings');
					}else if(reviewlenth == 2){
						$(".ratings").addClass('ratings-two');
						$(".ratings").removeClass('ratings');
					}else if(reviewlenth == 5){
						$(".ratings").addClass('ratings-four');
						$(".ratings").removeClass('ratings');
					}else if(reviewlenth > 5){
						$(".ratings").addClass('ratings-more-four');
						$(".ratings").removeClass('ratings');
					}
					}
				}
				}				
              }, 3000);
		});     
                
	});</script>
