<?php if ($this->getAttributeSetName() != "Accessories") { ?>
<div class="ratings">
	<span class="glyphicon glyphicon-star rating orange" aria-hidden="true"></span>
	<span class="glyphicon glyphicon-star rating orange" aria-hidden="true"></span>
	<span class="glyphicon glyphicon-star rating orange" aria-hidden="true"></span>
	<span class="glyphicon glyphicon-star rating gray" aria-hidden="true"></span>
	<span class="glyphicon glyphicon-star rating gray" aria-hidden="true"></span>
	&nbsp;(3256 avis)
</div>
<?php } ?>


<?php if ($this->getAttributeSetName() == "Accessories") { ?>
    <?php
    $_product = $block->getProduct();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
	$priceLabel = $block->getPriceLabel(); 
    ?>
<div class="col-sm-6">
    <form action="<?php echo $this->getAccessoriesCartUrl($_product->getId()); ?>" method="post">
    <div class="pull-right grey-strip margin-xs-b-s" id="cart_add_data">
            <a class="btn btn-primary pull-right hidden-sm hidden-xs margintop4 device-cart" href="<?php echo $block->getAddCartUrl($_product->getSku()) ?>"><?php /* @escapeNotVerified */ echo __('Commander') ?></a>
        <h5 class=""><?php /* @escapeNotVerified  echo __('Notre offre')*/ ?></h5>
        <h4 class="orange"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($_product->getTierPrice(1,$_product), 2), true, false) ?></h4>
		<span class="orange"><?php echo $priceLabel; ?></span>
        <a class="btn btn-primary visible-sm-block visible-xs-block margin-xs-b-s mobile-width" href="<?php echo $this->getAccessoriesCartUrl($_product->getId()); ?>"><?php /* @escapeNotVerified */ echo __('Commander') ?></a>
            <?php echo $block->getBlockHtml('formkey') ?>
            <?php echo $block->getChildHtml('form_top'); ?>
            <?php echo $block->getChildHtml('form_bottom'); ?>
    </div>
    </form>
</div>
<?php } ?>

