<?php if (($this->getAttributeSetName() == "Accessories" || $this->getAttributeSetName() == "handset") && $block->getProduct()->getObsoleteDevice() == 0) { ?>

<article class="node node-layer-columns layer-style--gray clearfix">				
    <div class="container">
	<?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
            //getting current store id                                                                                                                                                                                                                     
            $storeCode = $storeManager->getStore()->getName();
			if ($storeCode == 'French') { 
                $url = 'https://www.orange.be/fr/support/appareils/livraison';
            } else {
                $url = ' https://www.orange.be/nl/hulp/toestellen/levering';
            }
            ?>
   <p><?php echo __("Livraison rapide et gratuite, même le samedi. Retour simple et sans frais.");?> <a href="<?php echo $url;?>" class="orange"  target="_blank" rel="noopener noreferrer"><?php echo __("Plus d’infos");?></a></p>
</div>
</article>

<?php } ?>
