<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>

<?php $parentItem = $block->getItem() ?>

<?php $items = array_merge([$parentItem->getOrderItem()], $parentItem->getOrderItem()->getChildrenItems()) ?>
<?php $shipItems = $block->getChildren($parentItem) ?>

<?php if ($block->getItemOptions() || $parentItem->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>

    <?php if ($_item->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php if (!$_item->getParentItem() || $_item->getParentItem() && $_item->getParentItem()->getProduct()->getData(\Dilmah\Catalog\Helper\Data::IS_PACK_PRODUCT_ATTRIBUTE) != 1): ?>
    <?php if (!$_item->getParentItem()): ?>
        <tr class="bundle-item bundle-parent">
            <td class="item-info">
                <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
                <p class="sku"><?= /* @escapeNotVerified */  __('SKU'); ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
            </td>
    <?php else: ?>
        <tr class="bundle-item bundle-option-value">
            <td class="item-info">
                <p><?= $block->getValueHtml($_item)?></p>
            </td>
    <?php endif; ?>
            <td class="item-qty">
                <?php if (($block->isShipmentSeparately() && $_item->getParentItem()) || (!$block->isShipmentSeparately() && !$_item->getParentItem())): ?>
                    <?php if (isset($shipItems[$_item->getId()])): ?>
                        <?php
                        $isPack = $_item->getProduct()->getData(\Dilmah\Catalog\Helper\Data::IS_PACK_PRODUCT_ATTRIBUTE) == 1;
                        $packSize = $_item->getProduct()->getData(\Dilmah\Catalog\Helper\Data::PACK_SIZE_ATTRIBUTE);
                        ?>
                        <?= /* @escapeNotVerified */  $shipItems[$_item->getId()]->getQty() * 1 ?>
                        <?php if ($isPack && $packSize): ?>
                            <?php echo __("(%1 packs)", $shipItems[$_item->getId()]->getQty()*1 * $packSize) ?>
                        <?php endif ?>
                    <?php elseif ($_item->getIsVirtual()): ?>
                        <?= /* @escapeNotVerified */  __('N/A') ?>
                    <?php else: ?>
                        0
                    <?php endif; ?>
                <?php else: ?>
                    &nbsp;
                <?php endif; ?>
            </td>
        </tr>
    <?php endif; ?>
<?php endforeach; ?>

<?php if ($_showlastRow): ?>
    <tr>
        <td colspan="2" class="item-extra">
            <?php if ($block->getItemOptions()): ?>
            <dl>
                <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                            <dd><?= /* @escapeNotVerified */  $option['value'] ?></dd>
                <?php endforeach; ?>
            </dl>
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
    </tr>
<?php endif; ?>
