<?php $_order = $block->getOrder(); ?>
<?php $items = $_order->getAllItems(); ?>
<?php $TypeId = ''; ?>
    <?php foreach ($items as $item) { ?>        
		<?php //echo $item->getProduct()->getTypeId();  ?>
        <?php
        if ($item->getProduct()->getTypeId() == 'bundle'  && $item->getParentItemId() != "") {
            $childrens = $item->getChildrenItems();
            foreach ($childrens as $childs) {
                if ($childs->getProduct_type() == 'virtual') {
                    echo $itemName = $childs->getName();                    
                }
            }
            ?>
        <?php } ?>        
    <?php } ?>    


