<?php $_order = $block->getOrder(); ?>
<?php $items = $_order->getAllItems(); ?>
<?php $TypeId = ''; ?>

    <?php foreach ($items as $item) { ?>        
		<?php //echo $item->getProduct()->getTypeId();  ?>
        <?php				
        if ($item->getProduct()->getTypeId() == 'virtual' && $item->getProduct()->getParentItemId() == '') {
            echo  $item->getName() ;            
        }
        ?>  
    <?php } ?>    


