<?php
/**
 * Copyright © 2015 Netstarter. All rights reserved.
 *
 * PHP version 5
 *
 * @category  PHP
 * @author    Netstarter M2 Stack Team <contact@netstarter.com>
 * @copyright 2007-2015 NETSTARTER PTY LTD (ABN 28 110 067 96)
 * @license   licence.txt ©
 * @link      http://netstarter.com.au
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation state
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */
?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
    <div class="filter-current">
        <strong class="block-subtitle filter-current-subtitle"
                role="heading"
                aria-level="2"
                data-count="<?php echo count($_filters); ?>"><?php /* @escapeNotVerified */
            echo __('Your selection:') ?></strong>
        <?php //Removed filtering display from left nav as per Dilmah design ?>
            <ol class="items">
                <?php
                $counter = 1;
                $styleFirst = '';
                foreach ($_filters as $_filter):
                    if ($counter == 1):
                        $styleFirst = ' first';
                    else:
                        $styleFirst = '';
                    endif;
                    $counter ++;
                    ?>
                    <li class="item <?php echo $styleFirst; ?>">
                        <span class="filter-label"><?php echo $block->escapeHtml(__($_filter->getName())); ?></span>
                        <?php $filterLabels = $_filter->getLabel()?>
                        <?php if (!is_array($filterLabels)):?>
                            <span class="filter-value"><?php /* @escapeNotVerified */ echo __($block->stripTags($_filter->getLabel())) ?></span>
                        <?php else:?>
                            <?php $filterLabelString= implode(", ",$filterLabels); $lastFilter = end($filterLabels)?>
                            <?php foreach ($filterLabels as $filterLabel):?>
                                <span class="filter-value"><?php /* @escapeNotVerified */ echo __($block->stripTags(trim($filterLabel)))?></span>
                                <span class="filter-value"><?php echo ($lastFilter != $filterLabel ? ', ' : '')?></span>
                            <?php endforeach;?>
                        <?php endif; ?>
                        <span class="filter-value"><?php /* @escapeNotVerified */ //echo $block->stripTags($_filter->getLabel()) ?></span>
                        <?php
                        $clearLinkUrl = $_filter->getClearLinkUrl();
                        if (!is_array($filterLabels))
                            $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " . $block->stripTags($_filter->getLabel());
                        else
                            $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " . $block->stripTags($filterLabelString);
                        if ($clearLinkUrl):
                            ?>
                            <a class="action previous" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                               title="<?php /* @escapeNotVerified */ echo __('Previous') ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Previous') ?></span>
                            </a>
                            <a class="action remove"
                               title="<?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                               href="<?php /* @escapeNotVerified */ echo $clearLinkUrl ?>">
                                <span><?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                            </a>
                        <?php else: ?>
                            <a class="action remove" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                               title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Remove')) . " " . $currentFilterName;?>">
                                <span><?php /* @escapeNotVerified */ echo __('Remove This Item') ?></span>
                            </a>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ol>
    </div>
<?php endif; ?>