<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div id="gift-options-cart" data-bind="scope:'giftOptionsCart'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#gift-options-cart": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.giftOptionsConfig = <?php /* @escapeNotVerified */ echo $block->getGiftOptionsConfigJson(); ?>;
        window.currentStoreId = <?php /* @escapeNotVerified */ echo $this->helper('Dilmah\Catalog\Helper\Data')->getStoreId(); ?>;
        window.globalStoreId = <?php /* @escapeNotVerified */ echo \Dilmah\Catalog\Helper\Data::GLOBAL_STORE_ID; ?>;
    </script>
</div>
