<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category    Dilmah
 * @package     Dilmah_SiteMap
 * @author      Netstarter Team <contact@netstarter.com>
 * @copyright   Copyright (c) 2015 Netstarter Pty Ltd. (http://www.netstarter.com.au)
 */

?>
<div class="sitemap-top-categorys">
    <?php echo $block->getChildHtml('catalog.mainnav.sitemap'); ?></div>
<div class="sitemap-bottom-navigation">
    <?php echo $block->getChildHtml('sitemap.bottom.content'); ?>
</div>

