<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
<?php
$helper      = $this->helper('Lof\LazyLoad\Helper\Data');
$loadingIcon = $helper->getConfig('general/loadingIcon');
$imgSrc      = $helper->getMediaUrl() . 'lof/lazyload/' . $loadingIcon;

?> <?php if ($helper->isEnable()) { ?>
         src="<?php echo $imgSrc ?>"
            />
        <noscript><img class="lof-lazy product-image-photo"
             <?php /* @escapeNotVerified */ echo $block->getCustomAttributes(); ?>
             src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
             width="<?php /* @escapeNotVerified */ echo $block->getResizedImageWidth(); ?>"
             height="<?php /* @escapeNotVerified */ echo $block->getResizedImageHeight(); ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>"/></noscript>

        <?php } ?>
         
   
